[package]
name = "didkit-http"
version = "0.0.1"
authors = ["Charles E. Lehner <charles.lehner@spruceid.com>"]
edition = "2018"

[dependencies]
didkit = { path = "../lib" }
tokio = { version = "0.2", features = ["macros", "stream"] }
structopt = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bytes = "0.5"
hyper = "0.13"
tower-service = "0.3"
futures-util = { version = "0.3", default-features = false }
