name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: didkit

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout DIDKit repository
      uses: actions/checkout@v2
      with:
        path: didkit

    - name: Checkout SSI library
      uses: actions/checkout@v2
      with:
        repository: spruceid/ssi
        token: ${{ secrets.GH_ACCESS_TOKEN_CEL }}
        path: ssi

    - name: Cache Cargo registry and build artifacts
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml', '**.rs') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build
      run: cargo build --verbose --workspace

    - name: Test
      run: cargo test --verbose --workspace
